### ISSUE TITLE
Créditos

### ISSUE THREAD

**Issue by zanaca** [cybers-athletic/Desafios#2]
Bom saber que inspiramos desafios!

**Comment by sl4ureano** [comment]
@zanaca 
Estão inspirando sim. Estamos organizando os desafios ainda. Por isso não demos os devidos créditos aos criadores de alguns desafios. Seus merecidos créditos estão em https://github.com/cybers-athletic/challenge-delta.

Obs: O pessoal do Hotel Urbano poderiam ter pelo menos me dado um feedback no desafio que cumpri para uma oportunidade para Desenvolvedor.

**Comment by sl4ureano** [comment]
@zanaca Aceitamos contribuições de novos desafios!
